[project]
name = "medagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "datasets>=4.3.0",
    "ipykernel>=7.0.1",
    "pillow>=12.0.0",
    "requests>=2.32.5",
    "torch>=2.9.0",
]
